server {
  listen 8080;
  server_name _;
  absolute_redirect off;
  root /usr/share/nginx/html;
  index index.html;
  location / { try_files $uri $uri/ =404; }
  location = /config.json { add_header Cache-Control "no-store"; }
  error_page 404 /404.html;
}
